name: openmanufacturing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0.0
  - fastapi>=0.115.0
  - uvicorn>=0.34.0
  - pydantic>=2.11.0
  - sqlalchemy>=2.0.0
  - passlib>=1.7.4
  - python-jose>=3.3.0
  - httpx>=0.28.0
  - aiosmtplib>=4.0.0
  - redis-py>=6.0.0
  - pyjwt>=2.10.0
  - pytest>=8.3.0
  - pytest-asyncio>=0.26.0
  - pip:
    - python-multipart==0.0.20
    - cryptography>=41.0.0
    - prometheus-client>=0.19.0
    - psycopg2-binary>=2.9.9
    - aiomysql>=0.2.0 